"""empty message

Revision ID: f9d45906ecd1
Revises: fc6bcdb0befb
Create Date: 2020-01-30 14:15:50.198197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d45906ecd1'
down_revision = 'fc6bcdb0befb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_request', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_request', 'created_at')
    # ### end Alembic commands ###
